---
# vpc.yml - usage: ansible-playbook -i "localhost," -c local create-role.yml
- hosts: localhost

  tasks:
    - name: Create Role switch
      iam_policy:
        profile: infoaws
        iam_type: role
        iam_name: switch
        state: present
        policy_name: switchpolicy
        policy_document: "./switch.json"
        register: new_role
    - debug: var=new_role
    - name: Apply policy PowerUserAccess to switch ROLE
      iam_policy:
        profile: infoaws
        iam_type: policy
        iam_name: switch
        policy_name: "PowerUserSwitch"
        policy_document: terminate-policy.json
        state: present
        register: power
    - debug: var=power
    - name: Apply SAFE policy to switch ROLE
      iam_policy:
        profile: infoaws
        iam_type: policy
        iam_name: switch
        policy_name: "SafePolicy"
        policy_document: terminate-policy.json
        state: present
        register:
    - debug: var=power
